name: Run Checkstyle

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: java -jar checkstyle-13.2.0-all.jar -c checkstyle.xml src/